import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";



// Déclaration de la police Inria Sans

const inriaSans = localFont({
  src: "@/app/Fonts/InriaSans-Light.ttf",
  variable: "--font-inria-sans",
  weight: "400",
});
const Inter = localFont({
  src: "@/app/Fonts/Inter_18pt-Light.ttf",
  variable: "--font-Inter",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Inter.variable} ${inriaSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
