// app/layout.tsx ou RootLayout.tsx
import type { Metadata } from "next";
import NavBar from "./component/Navbar/NavBar";
import "./globals.css";
import { Footer } from "./ui/designSystem/component/Footer/Footer";
import LoaderWrapper from "../app/component/LoaderWrapper";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Utilisation du LoaderWrapper pour envelopper le contenu */}
        <LoaderWrapper>
          {" "}
          <NavBar />
          {children}
          <Footer />
        </LoaderWrapper>
      </body>
    </html>
  );
}
